-- OnRamp labs: shared schema for the database sessions deck.
-- Tenant ids are readable slugs ('acme') so plans and chat answers stay readable.
-- Production would use uuid, as on the row-level security slides.
-- No foreign key on orders.customer_id: db-01 measures index write cost, and a
-- per-row FK check would hide it.
SET client_min_messages = warning;  -- quiet the "does not exist, skipping" notices on first run
DROP TABLE IF EXISTS sessions, orders, users CASCADE;

CREATE TABLE users (
  id      bigint PRIMARY KEY,
  org_id  text   NOT NULL,
  email   text   NOT NULL
);
-- Refresher: lower(email) defeats a plain index, so the login lookup uses an expression index.
CREATE INDEX idx_users_email_lower ON users (lower(email));

CREATE TABLE orders (
  order_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      text          NOT NULL,
  customer_id bigint        NOT NULL,
  status      text          NOT NULL,
  created_at  timestamptz   NOT NULL,
  total       numeric(10,2) NOT NULL
);
-- Refresher and the "tenant first in the index" slide.
CREATE INDEX idx_orders_org_created ON orders (org_id, created_at);

CREATE TABLE sessions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token       text        NOT NULL,
  user_id     bigint      NOT NULL,
  expires_at  timestamptz NOT NULL
);
-- Refresher: hash index example.
CREATE INDEX idx_sessions_token ON sessions USING hash (token);
